name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  PROJECT_NAME: NewWorldAfkPreventer
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Create artifact
      run: |
        cd ./publish
        7z a ../${{ env.PROJECT_NAME }}-${{ github.ref_name }}.zip *

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-${{ github.ref_name }}
        path: ./${{ env.PROJECT_NAME }}-${{ github.ref_name }}.zip

  create-release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-${{ github.ref_name }}

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: ./${{ env.PROJECT_NAME }}-${{ github.ref_name }}.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
